### ISSUE TITLE
Sespis 3 definition of SI

### ISSUE THREAD

**Issue by mmr12** [alistairewj/sepsis3-mimic#12]
In Seymour's Assessment of Clinical Criteria for Sepsis supplemental material, he goes into details on the definition of suspicion of infection. In particular, he notes that only antibiotics that have been prescribed in bulk (ie more than one antibiotic prescribed) are relevant.

In abx-micro-prescription.sql [https://github.com/alistairewj/sepsis3-mimic/blob/master/query/tbls/abx-micro-prescription.sql](url) I would modify 
```
with abx as
(
  select pr.hadm_id
  , pr.drug as antibiotic_name
  , pr.startdate as antibiotic_time
  , pr.enddate as antibiotic_endtime
  from prescriptions pr
  -- inner join to subselect to only antibiotic prescriptions
  inner join abx_poe_list ab
      on pr.drug = ab.drug
)
```

to 

```
with abx_temp as
(
  select pr.hadm_id
  , pr.drug as antibiotic_name
  , pr.startdate as antibiotic_time
  , pr.enddate as antibiotic_endtime
  from prescriptions pr
  -- inner join to subselect to only antibiotic prescriptions
  inner join abx_poe_list ab
      on pr.drug = ab.drug
)
, abx_temp2 as 
(
  select hadm_id
  , antibiotic_time
  , case when count(antibiotic_name)>1 then 1 else 0 end as multiple_antibiotics
  from abx_temp
  group by hadm_id, antibiotic_time
)
, abx as 
(
  select abx.*
  from abx_temp abx
  right join abx_temp2 condition 
    on abx.hadm_id = condition.hadm_id
  where condition.multiple_antibiotics = 1
)
```
Seymour's supplemental material: [https://cdn.jamanetwork.com/ama/content_public/journal/jama/935012/joi160006supp1_prod.pdf?Expires=2147483647&Signature=d8tBNzfjAky82QEH0wUGy9sekA~He6eB4TwpanpeLQDKkuqZ0bEH-vJcoXwRPJCIbMOj-hZr5ENVcyeHDqGJJi5JR5oxrrkLWo1j3Dz~j0bPkjP4FiNXvjiI0X8s9EZmLMY7253OFq2lc8o-A2-bhLwi8F4lP7w6Ve7DT4bHqMCyaAKX7jOpJMh3RKrLPQgpL7dFmrofelpYI6uHo1EPrGuR76lDdN0RJxbHgJIqzkFhlA7t1XmsW5DBG-sANpZqI6gPNY650bwXCggLDJwbZ0Uvif-Qs8siOEaxkBRlkyve13KJfx07Gsg3z2RxDHXxohdQWGZL~bciOZHFtZAC~g__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA](url)

**Comment by alistairewj** [comment]
The problem with that approach is that you can have a single order for
multiple rounds of antibiotics.

**Comment by mmr12** [comment]
I see, thank you. Just a follow up question: would the prescription end time be an indicator? I.e. is it a valid assumption that a 1 day prescription period is for a single dose?

There are 419 cases of suspicion of infection (I am looking over the full hospital stay) that are determined by an (or multiple) antibiotic prescribed for a single day (and blood cultures taken of course)

**Comment by alistairewj** [comment]
It certainly would indicate multiple doses, but the end date of the
prescription isn't always there. You'd have to do a bit of investigation of
the antibiotics to see how well a rule like that worked. Definitely an
option though!

>
