### ISSUE TITLE
SOFA respiration

### ISSUE THREAD

**Issue by mmr12** [alistairewj/sepsis3-mimic#13]
Hi
Is there a reason why we exclude ventilated cases and only look at non ventilated cases for PaO2FiO2 between 200 and 400? I understand the novent exclusion for <200, but even if a patient is ventilated, then a PaO2FiO2 ratio below 400 should be considered worrisome? 

```  -- Respiration
  , case
      when PaO2FiO2_vent_min   < 100 then 4
      when PaO2FiO2_vent_min   < 200 then 3
      when PaO2FiO2_novent_min < 300 then 2
      when PaO2FiO2_novent_min < 400 then 1
      when coalesce(PaO2FiO2_vent_min, PaO2FiO2_novent_min) is null then null
      else 0
    end as respiration
```

Thanks!

**Comment by alistairewj** [comment]
Yeah it's a good catch you could/should probably incorporate both.
