### ISSUE TITLE
[Not an Issue but a question] Has there been similar Sepsis analysis conducted on eICU dataset? 

### ISSUE THREAD

**Issue by sosweet** [alistairewj/sepsis3-mimic#14]
Has there been similar analysis on eICU dataset like the Sepsis study done on MIMIC-III by @alistairewj and team?

Please let me know as I am interested to see how the research extends to different cohorts from other hospitals.

Thanks, 
Sri Kanth

Apologies for opening as an issue as I am not sure how to ask this question. I asked on OpenData forum but not sure if that is the right place to ask for this repo https://opendata.stackexchange.com/questions/15573/has-there-been-similar-analysis

**Comment by alistairewj** [comment]
The research hasn't been done to my knowledge, but it's quite difficult due to the lack of consistent microbiology data in eICU.

Questions here are fine!

**Comment by sosweet** [comment]
@alistairewj Thanks much for your quick reply.

To provide you with more specifics. I am working on an MLA that diagnoses and predicts Sepsis & Septic Shock using Vitals and GCS scores. I built this model based on MIMIC-III dataset.

Now I want to validate the generalizability of the model across hospitals, and eICU dataset seemed to contain data from a wide variety of hospitals.

What I need from the eICU data is
- ICD9 Diagnosis codes
- Vital Signs
- GCS Scores
- Suspicion of Infection [concomitant orders for antibiotics and blood cultures]
- To better identify the Onset of Sepsis/Shock need to calculate
     - Vasopressor presence
     - Whether on Ventilator
     - Values of   BILIRUBIN, CREATININE, PLATELET, INR, LACTATE

From what I can see in the raw data of eICU I should be able to accomplish calculating the above.

Please advice if my above analysis is incorrect. Thanks so much for your time.

Thanks,
Sri Kanth

**Comment by alistairewj** [comment]
> ICD9 Diagnosis codes

Nope. You have an active problem list via the diagnosis table. Often times I actually find the active problems to be more useful though. You have a single admission diagnosis via APACHE.

> Vital Signs

Yep.

> GCS Scores

Yep.

> Time of Suspicted infection [concomitant orders for antibiotics and blood cultures]

Not really - or at least not consistently across all hospitals. You might get lucky with a few.

> And SOFA score at time of infection

Calculating SOFA is definitely possible.

**Comment by sosweet** [comment]
thanks so much @alistairewj 

I will do more due diligence on the eICU and report back any positive findings in the event others in the community might benefit.

**Comment by alistairewj** [comment]
Great!
