### ISSUE TITLE
Suspicion of Infection time seems wrongly calculated. 

### ISSUE THREAD

**Issue by sreered** [alistairewj/sepsis3-mimic#15]
@alistairewj @tompollard Suspicion of Infection seems wrongly calculated abx-micro-prescription.sql

According to Seymour [et al] , time of suspected infection =  either the culture time (if before antibiotic), or the antibiotic time

But in abx-micro-prescription.sql, suspected_infection_time is set as coalesce(last72_charttime,next24_charttime) [line: 109]. As a result suspected_infection_time is set to blood culture irrespective of whether it happens before or after Antibiotic time.

Shouldn't it be set as coalesce(last72_charttime,**antibiotic_time**) instead?

Thanks for looking into this.

-Sree

**Comment by alistairewj** [comment]
Yeah that seems pretty reasonable!

**Comment by sosweet** [comment]
thanks @alistairewj for your reply. Do we need to fix it in the repo? Do you want me to do a simple pull request?

Or do you want to leave it as is, and let future researchers decide how to calculate the suspicion of infection?

**Comment by alistairewj** [comment]
The DOI from the paper links to v1, so it's fine to update this repo to best reflect the appropriate analysis. I can do that if you wish but since you brought it up it seems more appropriate for you to make a PR!

Will probably also make a version in the mimic code repository when I find the time.

**Comment by sreered** [comment]
Thanks @alistairewj, opened a PR.

**Comment by alistairewj** [comment]
Merged in #16 cheers!
