### ISSUE TITLE
I met a question when running SOFA_si.sql

### ISSUE THREAD

**Issue by Brandon96-lab** [alistairewj/sepsis3-mimic#17]
Sorry for bothering you.

When I ran the _SOFA_si.sql_, it informed me that:
ERROR:  column s.si_starttime does not exist
LINE 27:     between s.si_starttime

And I found the original code in _SOFA_si.sql_ are as follows:

vaso_mv as
(
  select ie.icustay_id
-- case statement determining whether the ITEMID is an instance of vasopressor usage
, max(case when itemid = 221906 then rate end) as rate_norepinephrine
, max(case when itemid = 221289 then rate end) as rate_epinephrine
, max(case when itemid = 221662 then rate end) as rate_dopamine
, max(case when itemid = 221653 then rate end) as rate_dobutamine
from suspinfect_poe s
inner join icustays ie
   on s.icustay_id = ie.icustay_id
inner join inputevents_mv mv
   on ie.icustay_id = mv.icustay_id
     and mv.starttime
between s.si_starttime
     and s.si_endtime
    where itemid in (221906,221289,221662,221653)

But when I found and opened the table _suspinfect_poe_, I couldn't find the column _si_starttime_and _si_endtime_. 
The sql code named as _suspicion-of-infection.sql_ establishing the table _suspinfect_poe_ is as follows:

DROP TABLE IF EXISTS suspinfect_poe CASCADE;
CREATE TABLE suspinfect_poe as
with abx as
(
  select icustay_id
, suspected_infection_time
, specimen, positiveculture
, antibiotic_name
, antibiotic_time
, ROW_NUMBER() OVER
(
PARTITION BY icustay_id
ORDER BY suspected_infection_time
) as rn
from abx_micro_poe
)
select
ie.icustay_id
, antibiotic_name
, antibiotic_time
, suspected_infection_time
, specimen, positiveculture
from icustays ie
left join abx
  on ie.icustay_id = abx.icustay_id
  and abx.rn = 1
order by ie.icustay_id;

I am a new learner of sql and mimic, and the question bothers me a lot. Your help will be much appreciated. @alistairewj @tompollard

**Comment by Brandon96-lab** [comment]
I have found the key to solve the problem.

**Comment by bugaosu** [comment]
hey how do you solve with the problem?
