### ISSUE TITLE
sepsis3 cohort for mimic-iv

### ISSUE THREAD

**Issue by heors** [alistairewj/sepsis3-mimic#19]
Greetings, I am trying to convert the **sepsis3-get-data.ipynb** notebook to extract SOFA scores and hence the dataset of sepsis3 patients. I noticed that you mostly need to modify **make-tables.sql**, however, since the number of queries is high, would the best approach be to try designing your own queries or would you recommend some approach for the conversion, for example how to set search paths for different tables in mimic-iv? Thank you.

**Comment by alistairewj** [comment]
I would just use our sepsis-3 branch on MIMIC-IV: https://github.com/MIT-LCP/mimic-iv/tree/sepsis3-related

Hoping to merge it soon after some double checking.

**Comment by heors** [comment]
Thank you. Does it mean that scripts used in/tbls would be still valid for mimic-iv? And if that is the case what should the search path be set to before running make-tables.sql since mimic-iv has multiple schemas?

**Comment by alistairewj** [comment]
They could certainly be adapted. It would use all three schemas (ICU data is in `mimic_icu`, hospital data incl labs/prescriptions is in `mimic_hosp`, and patient info including hosp admission info is in `mimic_core`).

**Comment by heors** [comment]
So can I just use scripts in sepsis-3 branch on MIMIC-IV independently from the notebook and get sofa and sepsis 3 patients scv file from it? Or do I need to use the notebook and modify **make-tables.sql**, both tables creation and to use new mimic-iv branch scripts as a submodule? My goal is just to get the csv file with patients that would fall under sepsis 3, I'm trying to find the fastest approach. Thank you

**Comment by alistairewj** [comment]
The sepsis-3 branch of the MIMIC-IV repository works independently of this repository.

**Comment by heors** [comment]
I see, thank you so much for your help. I have just one more question, if I want to extract sepsis3 cohort in what order would I have to run the queries in the /concepts in branch: `sofa.sql` had some prerequisites and I am also assuming `sepsis3.sql` has those as well?

**Comment by alistairewj** [comment]
Right - there is a make concepts file I have yet to commit to that repo which has the order of the queries. If I haven't fixed it by the end of the day please do re-raise this as an issue in the MIMIC-IV GitHub repo.

**Comment by heors** [comment]
Will do. Thank you for your help.
