### ISSUE TITLE
Error in make tables

### ISSUE THREAD

**Issue by zzzace2000** [alistairewj/sepsis3-mimic#4]
Hi, when I try to install, I find this error message. Can you help check it out?
Thanks!

mimic=# \i make-tables.sql 
SET
BEGIN
DROP TABLE
SELECT 156
DROP TABLE
SELECT 1268126
DROP TABLE
SELECT 61532
DROP TABLE
SELECT 61532
DROP TABLE
SELECT 61532
DROP MATERIALIZED VIEW
SELECT 58976
psql:../mimic-code/concepts/sepsis/martin.sql:8: NOTICE:  materialized view "martin_sepsis" does not exist, skipping
DROP MATERIALIZED VIEW
SELECT 58976
psql:../mimic-code/concepts/sepsis/explicit.sql:6: NOTICE:  materialized view "explicit_sepsis" does not exist, skipping
DROP MATERIALIZED VIEW
SELECT 58976
DROP MATERIALIZED VIEW
SELECT 53359
DROP MATERIALIZED VIEW
psql:../mimic-code/concepts/firstday/ventilation-first-day.sql:26: ERROR:  relation "ventdurations" does not exist
LINE 11: left join ventdurations vd

**Comment by alistairewj** [comment]
Fixed in #5.
