### ISSUE TITLE
suspinfect Table in blood-gas-infect-time.sql

### ISSUE THREAD

**Issue by Anis-Sh** [alistairewj/sepsis3-mimic#7]
Hello,

I cannot find the query for "suspinfect" table. It is required on line 93 of file blood-gas-infect-time.sql

Thanks

**Comment by alistairewj** [comment]
In general there were a few ways to define suspicion of infection and we ended up purely using the prescriptions data. If you find a suspinfect it should be updated to suspinfect_poe. I've done that for most files in https://github.com/alistairewj/sepsis3-mimic/commit/635200f26763dcf370bee8fbdc72aa477c035f10

All adjunct queries are just made available for your reference - caveat emptor!
