### ISSUE TITLE
Put These Benchmarks on Binder?

### ISSUE THREAD

**Issue by jzf2101** [alistairewj/sepsis3-mimic#8]
I saw your talk on MIMIC-III at the reproducibility workshop at ICML.  I'm a maintainer of binder, which is an open source project from Project Jupyter that we presented at the workshop. I'd like to figure out how to containerize this repository so we can share it on mybinder.org.  I can work on making a PR.

**Comment by jzf2101** [comment]
- [ ] `start` file to fire up database
- [ ] config specs
- [ ] postBuild file to run everying using nbconvert
- [ ] `verify` file to assert that notebook has been run

**Comment by jzf2101** [comment]
See https://github.com/jupyter/repo2docker/issues/93

**Comment by alistairewj** [comment]
So I added a branch for this and added some requirements/files. Outstanding issues are:

1. Not sure whether to build a postgres database from a .backup, or use an sqlite file. The SQL code is written to work with postgres, but it's easier to download/connect to an SQLite file.
2. The MIMIC demo file doesn't exist at the current URL
3. I haven't tried to run it yet - should the entire analysis be in a single jupyter notebook?

Probably won't have time to do much more before the demonstration you have as I'm abroad :/

**Comment by jzf2101** [comment]
NP we can talk about it more later 👍
